package cn.zzdz.common.entity.device;

import java.util.Date;

public class GroupInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.company_id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.model
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private Short model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.type
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.name
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.remark
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.gmt_creat
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private Date gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_group_info.gmt_modified
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.id
     *
     * @return the value of device_group_info.id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.id
     *
     * @param id the value for device_group_info.id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.company_id
     *
     * @return the value of device_group_info.company_id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.company_id
     *
     * @param companyId the value for device_group_info.company_id
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.model
     *
     * @return the value of device_group_info.model
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public Short getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.model
     *
     * @param model the value for device_group_info.model
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setModel(Short model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.type
     *
     * @return the value of device_group_info.type
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.type
     *
     * @param type the value for device_group_info.type
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.name
     *
     * @return the value of device_group_info.name
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.name
     *
     * @param name the value for device_group_info.name
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.remark
     *
     * @return the value of device_group_info.remark
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.remark
     *
     * @param remark the value for device_group_info.remark
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.gmt_creat
     *
     * @return the value of device_group_info.gmt_creat
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public Date getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.gmt_creat
     *
     * @param gmtCreat the value for device_group_info.gmt_creat
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setGmtCreat(Date gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_group_info.gmt_modified
     *
     * @return the value of device_group_info.gmt_modified
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_group_info.gmt_modified
     *
     * @param gmtModified the value for device_group_info.gmt_modified
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}