package cn.zzdz.common.entity.device;

import java.util.Date;

public class DeviceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.company_id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.pid
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.name
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.hardware_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Short hardwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.software_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Short softwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.enabled_flag
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Boolean enabledFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Short deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.comm_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Short commType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.usage_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Short usageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.imei
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.device_sn
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String deviceSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.lng
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.lat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.address
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.remark
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.gmt_creat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Date gmtCreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.gmt_modified
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.id
     *
     * @return the value of device_info.id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.id
     *
     * @param id the value for device_info.id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.company_id
     *
     * @return the value of device_info.company_id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.company_id
     *
     * @param companyId the value for device_info.company_id
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.pid
     *
     * @return the value of device_info.pid
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.pid
     *
     * @param pid the value for device_info.pid
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.name
     *
     * @return the value of device_info.name
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.name
     *
     * @param name the value for device_info.name
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.hardware_version
     *
     * @return the value of device_info.hardware_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Short getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.hardware_version
     *
     * @param hardwareVersion the value for device_info.hardware_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setHardwareVersion(Short hardwareVersion) {
        this.hardwareVersion = hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.software_version
     *
     * @return the value of device_info.software_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Short getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.software_version
     *
     * @param softwareVersion the value for device_info.software_version
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setSoftwareVersion(Short softwareVersion) {
        this.softwareVersion = softwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.enabled_flag
     *
     * @return the value of device_info.enabled_flag
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Boolean getEnabledFlag() {
        return enabledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.enabled_flag
     *
     * @param enabledFlag the value for device_info.enabled_flag
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setEnabledFlag(Boolean enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_type
     *
     * @return the value of device_info.device_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Short getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_type
     *
     * @param deviceType the value for device_info.device_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setDeviceType(Short deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.comm_type
     *
     * @return the value of device_info.comm_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Short getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.comm_type
     *
     * @param commType the value for device_info.comm_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setCommType(Short commType) {
        this.commType = commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.usage_type
     *
     * @return the value of device_info.usage_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Short getUsageType() {
        return usageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.usage_type
     *
     * @param usageType the value for device_info.usage_type
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setUsageType(Short usageType) {
        this.usageType = usageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.imei
     *
     * @return the value of device_info.imei
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.imei
     *
     * @param imei the value for device_info.imei
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.device_sn
     *
     * @return the value of device_info.device_sn
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.device_sn
     *
     * @param deviceSn the value for device_info.device_sn
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn == null ? null : deviceSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.lng
     *
     * @return the value of device_info.lng
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.lng
     *
     * @param lng the value for device_info.lng
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.lat
     *
     * @return the value of device_info.lat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.lat
     *
     * @param lat the value for device_info.lat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.address
     *
     * @return the value of device_info.address
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.address
     *
     * @param address the value for device_info.address
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.remark
     *
     * @return the value of device_info.remark
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.remark
     *
     * @param remark the value for device_info.remark
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.gmt_creat
     *
     * @return the value of device_info.gmt_creat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Date getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.gmt_creat
     *
     * @param gmtCreat the value for device_info.gmt_creat
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setGmtCreat(Date gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.gmt_modified
     *
     * @return the value of device_info.gmt_modified
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.gmt_modified
     *
     * @param gmtModified the value for device_info.gmt_modified
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}