package cn.zzdz.device.dao;

import cn.zzdz.common.entity.device.DeviceInfo;
import cn.zzdz.common.entity.device.DeviceInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    long countByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int deleteByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    List<DeviceInfo> selectByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    DeviceInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int updateByExample(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Mon Mar 16 15:49:13 CST 2020
     */
    int updateByPrimaryKey(DeviceInfo record);
}