package cn.zzdz.device.dao;

import cn.zzdz.common.entity.device.GroupInfo;
import cn.zzdz.common.entity.device.GroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    long countByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int deleteByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    List<GroupInfo> selectByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    GroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByExample(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_group_info
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByPrimaryKey(GroupInfo record);
}