package cn.zzdz.device.dao;

import cn.zzdz.common.entity.device.GroupDeviceRelExample;
import cn.zzdz.common.entity.device.GroupDeviceRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupDeviceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    long countByExample(GroupDeviceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int deleteByExample(GroupDeviceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int deleteByPrimaryKey(GroupDeviceRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int insert(GroupDeviceRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int insertSelective(GroupDeviceRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    List<GroupDeviceRelKey> selectByExample(GroupDeviceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") GroupDeviceRelKey record, @Param("example") GroupDeviceRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_device_rel
     *
     * @mbg.generated Tue Mar 17 15:37:34 CST 2020
     */
    int updateByExample(@Param("record") GroupDeviceRelKey record, @Param("example") GroupDeviceRelExample example);
}